# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorited',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quote', to='belt_exam2.Quote'),
        ),
    ]
